### ISSUE TITLE
The loop does not break on success of @beforemethod

### ISSUE THREAD

**Issue by prafulkolhe89** [RationaleEmotions/website#11]
Was trying out this feature for my existing framework and encountered  that @beforemethod does get triggered for 4 times in case of failure, but the loop is not broken in case of Assertion Pass.

Below is the code snippet 

```
private int counter = 1;
@BeforeMethod()
	@Retriable(attempts = 4)
	public void setup(Method method) {
				initiate();
				System.out.println("Test name: " + method.getName());
				AssertJUnit.assertEquals(2, counter++);
				LoginPageObj = new LoginPage();
				AgenciesLandingPageObj = new AgenciesLandingPage();
				utils = new CommonUtils();
				error_message = "";				
		}
```	

Further observed that the value for testResult in case of assertion getting passed (AssertJUnit.assertEquals) remains unchanged while eventually does not break the loop here 

```
@Override
	  public void run(IConfigureCallBack callBack, ITestResult testResult) {
	    Retriable retriable =
	        testResult.getMethod().getConstructorOrMethod().getMethod().getAnnotation(Retriable.class);
	    int attempts = 1;
	    if (retriable != null) {
	      attempts = retriable.attempts();
	    }
	    for (int attempt = 1; attempt <= attempts; attempt++) {	
	      callBack.runConfigurationMethod(testResult);
	      if (testResult.getThrowable() == null) {
	        break;
	      }
	    }
	  }
```

Are there any more changes that are needed to resolve this ?

PS - current testng version used 
               <dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.3.0</version>
			<scope>compile</scope>
		</dependency>

**Comment by krmahadevan** [comment]
@prafulkolhe89 - Please refer to my comment in https://github.com/cbeust/testng/pull/2262#issuecomment-787456108
