### ISSUE TITLE
do you know how to get assertion infomation in testng listner?

### ISSUE THREAD

**Issue by woxiangbo** [RationaleEmotions/website#13]
Hi, 

I am suffuring by to get  assertion infomation in testng listner, could you help to give some adivices ? thank you

the issue link is : 
https://stackoverflow.com/questions/70105197/testng-how-to-get-assertion-infomation-in-testng-listner

thank you 💯

**Comment by krmahadevan** [comment]
@woxiangbo - Looks like you already got an answer for your question. Closing this issue.
