### ISSUE TITLE
Re- executing test cases without Retryanlyser

### ISSUE THREAD

**Issue by kalyankumar381** [RationaleEmotions/website#14]
Need to re execute test cases without using retry analyzer and re-executing test cases logs should be come same extent report

**Comment by krmahadevan** [comment]
As far as I know there is no way of doing this without a retry analyzer. 

Why do you NOT want to use it? Care to elaborate ?

Extent Reports is not provided by TestNG and am I not familiar with it. So you may have to reach out to a respective forum for that.
