### ISSUE TITLE
Getting The method getDriverPath(ChromeOptions, boolean) is undefined for the type SeleniumManager error

### ISSUE THREAD

**Issue by kalyankumar381** [RationaleEmotions/website#16]
Getting "The method getDriverPath(ChromeOptions, boolean) is undefined for the type SeleniumManager" error after updating selenium version 4.21 for below line of code

browserPath = SeleniumManager.getInstance().getDriverPath(options,false).getBrowserPath()

Checked the SeleniumManager class getDriverPath() method is not available. What is alternate method for  getDriverPath();

**Comment by krmahadevan** [comment]
@kalyankumar381 - You should be logging issues related to Selenium project on the Selenium github page instead of here. A

You can try something like below

```java
String path = SeleniumManager.getInstance().getBinaryPaths(List.of("--browser", "chrome")).getDriverPath();
System.err.println("====> " + path);
```
