### ISSUE TITLE
IAnnotation transform method is not disabling the test in testng

### ISSUE THREAD

**Issue by Buddy15** [RationaleEmotions/website#6]
Here my intention is , Based on the before method condition the `@Test` method needs to enabled or disabled But in the below code even though I am passing the test case name its not getting skipped ? Can anyone suggest me solution?

I need the `BeforeTestMethod` to check some logic in my actual code and based on that I have to enable the `@Test` in the class file    

    public class ListnerClass implements IAnnotationTransformer {
    public static String  testName;
    public void transform(ITestAnnotation iTest, Class testClass, Constructor testConstructor, Method method) {
		if(method.getName().equalsIgnoreCase(testName)) {
			iTest.setEnabled(false);
		}
		
	}

    public class TestNGTest3 {
    @BeforeMethod
	public void setUp(Method result) {
		System.out.println("This is the before Method getting name "+result.getName());
		if(result.getName().contains("3")) 
           {
			ListnerClass.testName=result.getName();

		}
	}
	
	@Test
	public void testMethod3() {
		System.out.println("This is the Method of Method");
	}
	
	@Test
	public void testMethod4() {

		System.out.println("Hi");
	}

	
		
	}

`TestNG.xml`
      
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
        <suite name=" Regression Suite">
	    <listeners>
		<listener class-name="com.listners.ListnerClass" />
	    </listeners>
	    <test thread-count="1" name="Test">
		<classes>
			<class name="com.test.TestNGTest3" />
		</classes>
	</test> 
    </suite> 

Output:
```
This is the before Method getting name testMethod3
This is the Method of Method
This is the before Method getting name testMethod4
Hi
```

**Comment by krmahadevan** [comment]
@Buddy15 - I think I have already answered your question on the selenium forums https://groups.google.com/g/selenium-users/c/Qp2YxXK9aoc/m/LIKLYJk_BwAJ

**Comment by Buddy15** [comment]
Thanks.Will check out and revert in case any additional help needed.

**Comment by Buddy15** [comment]
If you give an example for this implementation of your 2 possible ways it
would be a great help.

**Comment by krmahadevan** [comment]
@Buddy15 - You just need to club the learnings in these two posts and you should be able to do it on your own

1. https://rationaleemotions.com/building_dynamic_testng_suites/ (Tells you how to work with `IAlterSuiteListener`)
2. https://rationaleemotions.com/beanshell_in_testng/ (Tells you how to use bean shell)

**Comment by Buddy15** [comment]
Thanks.
