### ISSUE TITLE
could you help resolve the question of testng ?

### ISSUE THREAD

**Issue by woxiangbo** [RationaleEmotions/website#8]
Hi,  you are the best one in all people I know, could you help to resolve the testng question ? thank you very much~!!
https://stackoverflow.com/questions/65560984/in-parallel-dose-testng-will-not-continue-to-execute-until-all-tests-which-has?noredirect=1#comment115912664_65560984

**Comment by krmahadevan** [comment]
@woxiangbo - Thanks for waiting on me. I have been swamped with stuff at work and hence the delayed response. I have answered your SO question.
